name: LockChat
author: ValresMC
version: 1.0.0
api: [5.0.0]
main: Valres\LockChat\Main

permissions:
  lock.command:
    default: op
    description: "Permet de lock le chat."
  lock.bypass:
    default: op
    description: "Permet de parler pendant le lock du chat."